const app = require('express')()
const vhost=require('vhost')
const web=require('./module/web')
const api=require('./module/api')
const admin=require('./module/admin')
app.use(vhost('www.wt.com',web))
app.use(vhost('api.wt.com',api))
app.use(vhost('adm.wt.com',admin))
app.listen(80, () => console.log('Example app listening on port 80!'))